### ISSUE TITLE
jasypt-hibernate5 isn't available on maven repository

### ISSUE THREAD

**Issue by Shanky2304** [jasypt/jasypt#10]
I see it has been quite some time since hibernate-5 integration was released. I also see it listed as a release on the [official download page](http://www.jasypt.org/download.html). But for the life of me, I can't seem to find it on, maven repository. 

Any help is much appreciated.

**Comment by hokitorres** [comment]
Latest release of jasypt-hibernate5 is available at Maven Repository: https://repo1.maven.org/maven2/org/jasypt/jasypt-hibernate5/1.9.3/
