### ISSUE TITLE
Technical Support Expiration Date

### ISSUE THREAD

**Issue by Sergindra** [jasypt/jasypt#11]
Hello,

I work for a long-term project which requires strong and stable technical support for every software used.

I want to know how long you are providing technical support for Jasypt 1.9.2.

Please I appreciate so much that you can give me expiration dates for this software product or expectations of its EOL.

Thank you!
Sergi

**Comment by hokitorres** [comment]
This is an open source project, there is no techical support as for paid software. 

In this forum we can answer your issues but there is no legal warranty. The good part is that you can revise the code by yourself and contribute back to the community,
