### ISSUE TITLE
externalize SECRET outside XML

### ISSUE THREAD

**Issue by pcouas** [jasypt/jasypt#12]
Hi,

I have 20 batch processes on a shared server with Java Process launched as shared user
My old application is an Spring 2.5 and hibernate3 with persistence.xml and appication-spring-context.xml
I need to externalize SECRET password outside source code.
How could i externalise SECRET password ? i could not export variable "sys admin" is not agree, could i use an private keystore to store it ?
Bash files are considered like my code !

Regards
Phil

**Comment by hokitorres** [comment]
You can extend PBEConfig to retrieve passwords from a database, remote server, KeyStore... whichever mechanism suits you best.

Then, configure the encryptor with your implementation of PBEConfig:

        StandardPBEStringEncryptor encryptor = new StandardPBEStringEncryptor();
        encryptor.setConfig(yourImpementationOfPBEConfig);
