### ISSUE TITLE
Incorrect functionality or Javadoc for EncryptableProperties#get(Object)

### ISSUE THREAD

**Issue by jhult** [jasypt/jasypt#13]
The [Javadoc for `EncryptableProperties`](/jasypt/jasypt/blob/master/jasypt/src/main/java/org/jasypt/properties/EncryptableProperties.java#L51) states:

> Decryption is performed on-the-fly when the `getProperty(String)` or `getProperty(String, String)` methods are called, and **only** these two methods perform decryption (**note that neither `get(Object)` nor `toString()` do**). Load and store operations are not affected by decryption in any manner.

However, the [Javadoc for the `get(Object)` method](/jasypt/jasypt/blob/master/jasypt/src/main/java/org/jasypt/properties/EncryptableProperties.java#L197) states:

> Obtains the property value for the specified key (see `Hashtable#get(Object)` ), **decrypting** it if needed.

And, as can be seen by [the code](/jasypt/jasypt/blob/master/jasypt/src/main/java/org/jasypt/properties/EncryptableProperties.java#L209), `get(Object)` does actually perform decryption.

Either the Javadoc should be updated or `get(Object)` should not perform decryption.

**Comment by hokitorres** [comment]
You are right, the javadoc was a bit old.
Updated now.
