### ISSUE TITLE
Unable to decrypt database password in hibernate.cfg.xml

### ISSUE THREAD

**Issue by jmestizo** [jasypt/jasypt#2]
jasypt-hibernate5 is unable to decrypt entries in hibernate.cfg.xml
This happens because C3P0ConnectionProvider.configure(Map) gets called instead of EncryptedPasswordC3P0ConnectionProvider.configure(Properties).

EncryptedPasswordC3P0ConnectionProvider should override configure(Map) instead of overloading.

**Comment by s3b-** [comment]
Why is this closed? I'm asking, because I stumbled upon the same problem after updating to hibernate 5.
