### ISSUE TITLE
jasypt-1.9.3-dist.zip don't exists anymore

### ISSUE THREAD

**Issue by yannickdenimal** [jasypt/jasypt#23]
The distribution zip is no more available
https://github.com/jasypt/jasypt/releases/download/jasypt-1.9.3/jasypt-1.9.3-dist.zip

**Comment by hanndecl** [comment]
I found a version of the distro on the sourceforce pages
https://sourceforge.net/projects/jasypt/files/jasypt/jasypt%201.9.3/jasypt-1.9.3-dist.zip/download

**Comment by hokitorres** [comment]
Fixed now.
