### ISSUE TITLE
Maven plugins fails to encrypt properties with a closing parenthesis

### ISSUE THREAD

**Issue by JoaoGuilhermedeSa** [jasypt/jasypt#24]
As the titles says, if i have a property with a closing parenthesis and try to run the maven plugin, the plugin wont detect the rest of the value. 

EX: DEC(12#456T)AXC03)

In this case, only 12#456T would be encrypted by the maven plugin.

**Comment by hokitorres** [comment]
Jasypt expects encrypted configuration parameters to appear surrounded by ENC(...), not by DEC, and it won't fail in case of having closing parenthesis inside.

Could you provide more details on how are you using jasypt here, please?

**Comment by JoaoGuilhermedeSa** [comment]
LOL.

I opened an issue on the wrong project. 

My bad.
