### ISSUE TITLE
Haven't been able to compile / utilize / run any java files from this entire directory.

### ISSUE THREAD

**Issue by cmfunk** [jasypt/jasypt#4]
Simply trying to use StandardPBEStringEncryptor to encrypt my passwords and although I've spent hours reading up on user created packages and compiling multiple java files at once, I have still not been able to compile a single java file from this directory. My java script and this file are located in the same directories and I'm correctly calling the package, but due to the StandardPBEStringEncryptor.java calling a multitude of other packages, I am constantly getting a "Package does not exist." I have had no success with any help setting up / compiling java files from the website, nor from online help of user created packages. I was searching for a "How to setup" or "Introduction" but to no avail.

**Comment by hokitorres** [comment]
The easiest way is using Maven or any Java build automation tool of your choice.

For example, adding jasypt to your Maven 2 or Maven 3 project is very easy, you just need to add the corresponding dependency to your `pom.xml`:

```
    <dependency>
      <groupId>org.jasypt</groupId>
      <artifactId>jasypt</artifactId>
      <version>1.9.3</version>
      <scope>compile</scope>
    </dependency>
```

If you do not want to use Maven, you can download the jasypt jar from here:

    https://mvnrepository.com/artifact/org.jasypt/jasypt/1.9.3

and then compile your class with a command like this:

`C:> java -classpath C:\myDir\jasypt-1.9.3.jar mypackage.MyFile`
