### ISSUE TITLE
Password is not ASCII

### ISSUE THREAD

**Issue by nishiichinoe** [jasypt/jasypt#5]
I started to use Jasypt in spring-boot with the maven dependency:

               <dependency>
		    <groupId>com.github.ulisesbocchio</groupId>
		    <artifactId>jasypt-spring-boot-starter</artifactId>
		    <version>2.1.1</version>
		</dependency>

My spring-boot starter class has these annotations:

@EnableEncryptableProperties
@PropertySource(name="EncryptedProperties", value = "classpath:application.properties")

I encrypted my password like this:

java -cp jasypt-1.9.2.jar org.jasypt.intf.cli.JasyptPBEStringEncryptionCLI input="mySecret"
password=password algorithm=PBEWithMD5AndDES

and added the property like this to my application.properties:

server.ssl.key-store-password: ENC(jasyptEncString)

At start I have this command line argument: --jasypt.encryptor.password=mySecret

But it is failing with:

Failed to bind properties under 'server.ssl.key-store-password' to java.lang.String:

    Reason: Password is not ASCII

**Comment by hokitorres** [comment]
The jasypt-spring-boot-starter project is maintained here: https://github.com/ulisesbocchio/jasypt-spring-boot
